baseURL: "https://davidllerena.netlify.app"
languageCode: "en-us"
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagerSize : 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
##      url: /blogs
#      weight: 1
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Personal Web Page"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "David Llerena" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "David Llerena."
    subtitle: " "
    content: " "
    image: 
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "https://drive.google.com/file/d/1c4LO-RfsgZ8slGtE_oY7H_4aZpwt_khX/view?usp=sharing"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-researchgate
          url: https://www.researchgate.net/profile/David-Llerena-4
      
  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/david.gif"
    content: |-
      I am currently seeking a postdoctoral position after successfully defending my Ph.D. in December 2024 at the Laboratoire de Mathématiques et Modélisation d'Évry (LaMME). My doctoral research was conducted under the supervision of Diego Chamorro and Pierre-Gilles Lemarié-Rieusset.

      My research interests focus on the local regularity theory of weak solutions for models derived from fundamental fluid mechanics, including the Navier-Stokes equations, MHD equations, and micropolar equations
    skills:
      enable: true
      title: 
      index: true
      items:
                  

  # Experience
  experience:
    enable: false
    # title: "Custom Name"
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

     
  # Education
  education:
    enable: true
    #title: 
    index: false
    items:
      - title: "Ph.D in Mathematics"
        school:
          name: "Université Paris-Saclay,  Laboratoire de Mathématiques et Modélisation d'Évry"
          url: "http://www.math-evry.cnrs.fr/doku.php"
        date: "2021 - 2024"

        content: |-
          Thesis title: On the interdependence of variables in the study of some equations in fluid mechanics.

          Advisors: Diego Chamorro and Pierre-Gilles Lemarié-Rieusset. 

      - title: "Master degree in Mathematics"
        school:
          name: "Université Paris Saclay site Orsay"
          url: "https://www.imo.universite-paris-saclay.fr/fr/etudiants/masters/mathematiques-et-applications/m2/arithmetique-analyse-geometrie/"
        date: "2023 - 2024"
        content: |-
          M2 Analyse, Arithmétique, Géométrie 

          Master thesis: Étude de la régularité pour quelques équations de la mécanique des fluides.
       
        featuredLink:
          enable: true
          name: "Rapport"
          url: "https://www.amarun.org/images/amarun/materiales/tesis-maestria/Llerena_2021.pdf"
      - title: "BS.c. in Applied Mathematics"
        school:
          name: "Universidad Central del Ecuador"
          url: "https://www.uce.edu.ec"
          date: 2013-2018
        content: |-
          Thesis: Aproximate identities in the Schwarzs spaces. 

          Advisor: Borys Alvarez-Samaniego
  #Articles
  research:
    enable: true
    # title: "Custom Name"
    index: true
    items: 
      - name: "Partial regularity and L3-norm concentration effects around possible blow-up points for the micropolar fluid equations."
        journal: "Preprint"
        date: "2024"
        url1: "https://hal.science/hal-04600217"
        content: "Joint work with: Diego Chamorro"
      - name: "Partial suitable solutions for the micropolar equations and regularity properties.  "
        journal: "Accepted in: Annales Mathématiques Blaise Pascal"
        date: "2024"
        url1: "https://hal.science/hal-03971925v1/document"
        content: "Joint work with Diego Chamorro"
      - name: "Some remarks about the stationary Micropolar fluid equations: existence, regularity and uniqueness"
        journal: "Journal of Mathematical Analysis and Applications"
        date: "2024"
        url1: "hthttps://arxiv.org/abs/2306.04270"
        url2: "https://www.sciencedirect.com/science/article/abs/pii/S0022247X24001239"
        content: "Joint work with Diego Chamorro and Gaston Vergara-Hermosilla"
      - name: "A crypto-regularity result for the micropolar fluids equations"
        journal: "Journal of Mathematical Analysis and Applications"
        date: "2022"
        url1: "https://arxiv.org/abs/2206.00328"
        url2: "https://www.sciencedirect.com/science/article/abs/pii/S0022247X22009362" 
        content: "Joint work with Diego Chamorro"
      
      - name: "Interior ϵ-regularity theory for the solutions of the magneto-micropolar equations with a perturbation"
        journal: "Journal of Elliptic and Parabolic Equations"
        date: "2022"
        url1: "https://arxiv.org/pdf/2111.06653.pdf"
        url2: "https://link.springer.com/article/10.1007/s41808-022-00163-y" 
        content: "Joint work with Diego Chamorro"
      - name: "Approximate identities for the Schwartz space"
        journal: "Analysis and Mathematical Physics "
        date: "2021"
        url2: "https://link.springer.com/article/10.1007/s13324-020-00456-2"
        content: "Joint work with  Boris Alvarez-Samaniego and  Wilson Alvarez-Samaniego"

  conference:
    enable: true
    content: 
  
  Teaching:
    enable: true
    content:
        
      

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: "You can reach me at my mail <a href=mailto:david.llerena@univ-evry.fr> david.llerena@univ-evry.fr"
    btnName: 
    btnLink: 
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: 
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
